### ISSUE TITLE
Static width and layout of navbar in relation to browser window width

### ISSUE THREAD

**Issue by jmcichowicz** [responsively-org/website#17]
Hello.
Given you loaded the https://responsively.app/ website and scrolled down to a point where the background is light (optional, but makes the issue more visible).

- when extend the width of browser window then navbar doesn't follow resulting in a "gap" in top right side and visible asymmetry
- when compress the width of browser window then navabar menu items/links follow the compression in an insufficent pace

https://user-images.githubusercontent.com/10189641/149554816-3bafcc32-1cfd-424d-9fcc-2ab4f166a3b5.mov

Adding a video that illustrates the description above.
Looking forward to using the Responsively extension itself
Thanks, best of luck
JMC

**Comment by Paul0908** [comment]
Is this issue still relevant? If yes, I would love to fix this issue.

**Comment by rajatmohan22** [comment]
I have fixed the error, please do check and merge my pull request
