### ISSUE TITLE
Must have a better Footer

### ISSUE THREAD

**Issue by ARYAN-CODES-STAR** [responsively-org/website#20]
There must be a better UI for footer and also more social links and download button should be in better position for catching user exp

![image](https://user-images.githubusercontent.com/78686630/218326393-58fd5f61-7a08-4de5-8a95-3ce48754a587.png)

I want this issue to be assigned to me, so i could better the way it looks.

I am looking for size adjustment and color combination of background and elements there.

I am going to use Neomorphism like color combinate button with opacity while hover.

**Comment by manojVivek** [comment]
@ARYAN-CODES-STAR Thanks for your interest in this, I have moved the issue to the `website` repo where it belongs. 

I would love to see what you want to implement for the footer. Please go for it.

**Comment by ARYAN-CODES-STAR** [comment]
Hey thanks for assigning me, will PR by day after tomorrow.

**Comment by ARYAN-CODES-STAR** [comment]
Hello sir @manojVivek , 
![Git_responsively](https://user-images.githubusercontent.com/78686630/219731126-2e4019c3-4356-4c8d-9817-bc545f2c5a9e.png)
I am facing some problems in using Gatsby, Kindly help me out.

**Comment by manojVivek** [comment]
Did you run `yarn` to install the dependencies before trying to run the site?

**Comment by ARYAN-CODES-STAR** [comment]
i have intalled yarn but now getting these errors
I think i need to understand abut SSL, crypto config.
Will update my progress.
![image](https://user-images.githubusercontent.com/78686630/219972151-5da16ddf-1e7b-4ad8-a72d-af2103801726.png)

**Comment by manojVivek** [comment]
Thanks for your effort on this, but the website is now revamped to a new design and this is not relevant anymore.
