### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by teageto** [responsively-org/website#41]
# 🐞 Hovers of the buttons (webpage)

### ✍️ When you just slide over the buttons, the background changes a bit and start some lights, I think that's not part of design webpage.

After slide over the buttons : 
![image](https://github.com/responsively-org/responsively-app/assets/103292617/4ff45ea7-be0c-4a8a-bfb7-f5fa6b854ca6)

Before or when just scroll down : 
![image](https://github.com/responsively-org/responsively-app/assets/103292617/f887d9b9-c3ad-4db1-94c3-ad99215ffa3e)

**Comment by manojVivek** [comment]
I don't see this happening for me. Can you share your OS and browser details please?

**Comment by teageto** [comment]
Yeah, of course. 
My browser is 🦊 Firefox (Version 121.0 64-bit) and my OS is Windows 10 H / OS Build 19045.3803

**Comment by manojVivek** [comment]
Yes, can confirm this happens on Firefox on Mac as well.
